# Global variables
language: python
python:
    - "2.7"
env:
  global:
    - TOOLS_DIR=$HOME/build_tools
    - INSTALL_DIR=$HOME/build_tools/install
    - GNAT_INSTALLER=$TOOLS_DIR/gnat-community-installer
    - GNAT_LINUX_INSTALLER_URL=https://community.download.adacore.com/v1/a639696a9fd3bdf0be21376cc2dc3129323cbe42?filename=gnat-2020-20200818-x86_64-linux-bin
    - GNAT_OSX_INSTALLER_URL=https://community.download.adacore.com/v1/aefa0616b9476874823a7974d3dd969ac13dfe3a?filename=gnat-2020-20200818-x86_64-darwin-bin.dmg
os:
  - linux

# Cache directory that allows us to not download GNAT GPL every time, speeding
# up the process.
cache:
  directories:
    - $HOME/build_tools

install:
  - export PATH=$INSTALL_DIR/bin:$PATH
  - sh .travis-install.sh

script:
  # Build gnatcoll-core. Build only the static variant, as only one build is
  # enough to check for errors: extra builds makes the Travis job longer for no
  # gain.
  - make build-static

  # Run the testsuite. It will rebuild gnatcoll-core in gcov mode before
  # running the tests, so that we have a coverage report.
  - (cd testsuite; ./run-tests --gcov)

after_success:
  - bash <(curl -s https://codecov.io/bash)
