# Global variables
language: python
python:
    - "2.7"
env:
  global:
    - TOOLS_DIR=$HOME/build_tools
    - INSTALL_DIR=$HOME/build_tools/install
    - GNAT_INSTALLER=$TOOLS_DIR/gnat-community-installer
    - GNAT_LINUX_INSTALLER_URL=http://mirrors.cdn.adacore.com/art/5cdffc5409dcd015aaf82626
    - GNAT_OSX_INSTALLER_URL=http://mirrors.cdn.adacore.com/art/5ce0322c31e87a8f1d4253fa
os:
  - linux

# Cache directory that allows us to not download GNAT GPL every time, speeding
# up the process.
cache:
  directories:
    - $HOME/build_tools

install:
  - export PATH=$INSTALL_DIR/bin:$PATH
  - sh .travis-install.sh

script:
  # Build gnatcoll-core. Build only the static variant, as only one build is
  # enough to check for errors: extra builds makes the Travis job longer for no
  # gain.
  - make build-static

  # Run the testsuite. It will rebuild gnatcoll-core in gcov mode before
  # running the tests, so that we have a coverage report.
  - (cd testsuite; ./run-tests --gcov)

after_success:
  - bash <(curl -s https://codecov.io/bash)
