name = "gnatcoll"
version = "26.0.0"
description = "GNAT Components Collection - Core packages"
website = "https://github.com/adacore/gnatcoll-core"

licenses = "GPL-3.0-or-later WITH GCC-exception-3.1"
maintainers = ["chouteau@adacore.com"]
maintainers-logins = ["Fabien-Chouteau"]
project-files = ["gnatcoll.gpr",
                 "projects/gnatcoll_projects.gpr",
                 "core/gnatcoll_core.gpr",
                 "minimal/gnatcoll_minimal.gpr"]
tags = ["gnatcoll", "json", "email", "refcount", "projects", "gpr", "vfs"]

[configuration]
disabled = true

[gpr-externals]
GNATCOLL_ATOMICS = ["intrinsic", "mutex"]
GNATCOLL_BUILD_MODE = ["DEBUG", "PROD"]
GNATCOLL_OS = ["windows", "unix", "osx"]
LIBRARY_TYPE = ["static", "relocatable", "static-pic"]

[gpr-set-externals."case(os)".linux]
GNATCOLL_OS = "unix"
[gpr-set-externals."case(os)".macos]
GNATCOLL_OS = "osx"
[gpr-set-externals."case(os)".windows]
GNATCOLL_OS = "windows"

[gpr-set-externals]
GNATCOLL_VERSION = "26.0.0"
GNATCOLL_BUILD_MODE = "PROD"

[[depends-on]]
libgpr = ">=25.0.0"
gnat = ">=14"
