#!/usr/bin/env python
from common.drivers import TESTSUITE_ROOT_DIR
from common.common_testsuite import CommonTestsuite
from e3.fs import mkdir, sync_tree
import sys
import os


class AllTestsuites (CommonTestsuite):
    @property
    def default_withed_projects(self) -> list[str]:
        return ["gnatcoll_minimal", "gnatcoll_core", "gnatcoll_projects"]

if __name__ == "__main__":
    # Export location of Python used to run the testsuite. Some tests need
    # to easily locate it.
    os.environ["PYTHON_EXEC_PATH"] = os.path.abspath(sys.executable)

    # Sync tests from the new location
    mkdir(os.path.join(TESTSUITE_ROOT_DIR, "tests"))
    for project in ("minimal", "core", "projects"):
        run_tests_path = os.path.join(TESTSUITE_ROOT_DIR, project, "run-tests")
        sync_tree(
            os.path.join(TESTSUITE_ROOT_DIR, project, "tests"),
            os.path.join(TESTSUITE_ROOT_DIR, "tests", project),
            delete=True,
        )
    suite = AllTestsuites(os.path.dirname(__file__))
    sys.exit(suite.testsuite_main())
