MODULE=gnatcoll
PROJECT=gnatcoll
LIBNAME=lib${TARNAME}

include ../Makefile.conf

ifeq ($(WITH_SYSLOG),yes)
SRCDIRS=./ ../gnat/ ./syslog/ ./paragraph_filling/
else
SRCDIRS=./ ../gnat/ ./nosyslog/ ./paragraph_filling/
endif
