MODULE=sqlite
PROJECT=gnatcoll_${MODULE}
LIBNAME=lib${TARNAME}_${MODULE}

include ../Makefile.conf

ifeq (${WITH_POSTGRES},yes)
SRCDIRS=./sqlite/ ./sqlite/with_sqlite/
else
SRCDIRS=./sqlite/ ./sqlite/no_sqlite/
endif

all:     dirs buildall
clean:   cleanall
install: libinstall

ifeq (${LIBRARY_TYPE},static)
FPIC=
else
FPIC=-fPIC
endif

