MODULE=gnatlib
PROJECT=gnatlib
LIBNAME=lib${TARNAME}

include ../Makefile.conf

ifeq ($(WITH_SYSLOG),yes)
SRCDIRS=./ ./syslog/
else
SRCDIRS=./ ./nosyslog/
endif

all:     c_files buildall
clean:   cleanall
install: libinstall

c_files: obj/gnatlib/${GNATLIB_LIBRARY_TYPE}/gnatlib_support.o
obj/gnatlib/${GNATLIB_LIBRARY_TYPE}/gnatlib_support.o: gnatlib_support.c
	gcc -c ${FPIC} ${DEFS} $< -o $@


