MODULE=iconv
PROJECT=gnatcoll_${MODULE}
LIBNAME=lib${TARNAME}_${MODULE}

include ../Makefile.conf

ifeq (${WITH_ICONV},yes)
SRCDIRS=./iconv/ ./iconv/with_iconv/
else
SRCDIRS=./iconv/ ./iconv/no_iconv/
endif
