MODULE=tools
PROJECT=gnatcoll_${MODULE}

include ../Makefile.conf

ifeq (${WITH_TEMPLATES},yes)
SRCDIRS=./tools/ ./tools/templates/
else
SRCDIRS=./tools/ ./toosl/notemplates/
endif

buildall: gnatcoll_db2ada

gnatcoll_db2ada: force
	${GPRBUILD} -m -j${PROCESSORS} -P$(PROJECT) $@ -p -largs $(POSTGRES_PATH)

installbin: force
	$(CP) obj/gnatcoll_db2ada${EXE} $(bindir)
