MODULE=tools
PROJECT=gnatcoll_${MODULE}

include ../Makefile.conf

ifeq (${WITH_TEMPLATES},yes)
SRCDIRS=./tools/ ./tools/templates/
else
SRCDIRS=./tools/ ./toosl/notemplates/
endif

installbin: force
	$(CP) obj/gnatcoll_db2ada${EXE} $(bindir)
ifeq (${WITH_XREF},yes)
	$(CP) obj/gnatinspect${EXE} $(bindir)
endif
