MODULE=gnatlib
PROJECT=gnatlib
LIBNAME=lib${TARNAME}

include ../Makefile.conf

ifeq ($(WITH_SYSLOG),yes)
SRCDIRS=./ ./syslog/
else
SRCDIRS=./ ./nosyslog/
endif

all:     buildall
clean:   cleanall
install: libinstall

