MODULE=sqlite
PROJECT=gnatcoll_${MODULE}
LIBNAME=lib${TARNAME}_${MODULE}

include ../Makefile.conf

ifeq (${WITH_SQLITE},yes)
SRCDIRS=./sqlite/ ./sqlite/with_sqlite/
else
SRCDIRS=./sqlite/ ./sqlite/no_sqlite/
endif

