MODULE=gnatcoll
PROJECT=gnatcoll
LIBNAME=lib${TARNAME}

include ../Makefile.conf

ifeq ($(WITH_SYSLOG),yes)
SRCDIRS=./ ./syslog/
else
SRCDIRS=./ ./nosyslog/
endif

all:     dirs c_files buildall
clean:   cleanall
install: libinstall

c_files: obj/gnatcoll/${GNATCOLL_LIBRARY_TYPE}/gnatcoll_support.o
obj/gnatcoll/${GNATCOLL_LIBRARY_TYPE}/gnatcoll_support.o: gnatcoll_support.c
	$(CC) -c ${FPIC} ${DEFS} $< -o $@
