MODULE=gnatcoll
PROJECT=gnatcoll
LIBNAME=lib${TARNAME}

include ../Makefile.conf

ifeq ($(WITH_SYSLOG),yes)
SRCDIRS=./ ./syslog/ ./paragraph_filling/
else
SRCDIRS=./ ./nosyslog/ ./paragraph_filling/
endif

ifeq ($(GNAT_SOURCES),copy)
SRCDIRS+= ../gnat/
endif
