MODULE=postgres
PROJECT=gnatcoll_${MODULE}
LIBNAME=lib${TARNAME}_${MODULE}

include ../Makefile.conf

ifeq (${WITH_POSTGRES},yes)
SRCDIRS=./postgres/ ./postgres/with_postgres/
else
SRCDIRS=./postgres/ ./postgres/no_postgres/
endif


